package config

const (
	Project     = "origen"
	PackageName = "application"
	WebSite     = `https://origadmin.com`
)

// UI generated by https://patorjk.com/software/taag/#p=display&f=Graffiti&t=Origen
const UI = `
________        .__                      
\_____  \_______|__| ____   ____   ____  
 /   |   \_  __ \  |/ ___\_/ __ \ /    \ 
/    |    \  | \/  / /_/  >  ___/|   |  \
\_______  /__|  |__\___  / \___  >___|  /
        \/        /_____/      \/     \/ 
`
